"""The demo-profile catalogue and its import, so the picker is a button rather than a CLI.

Ten deliberately poor-quality businesses across ten industries, generated by
`generator_data`, exist so the audit has something to find: the seeded world is twelve
healthy dental clinics and demos badly. Nothing here generates or scores anything itself
— it reads the catalogue, writes the chosen profiles into the caller's organization, and
stops. Running the audit is the user's next, separate step.

Scoped like every other router: `CurrentUser`, `DbSession`, `OrganizationId`. Another
tenant sees none of it, and `imported` reflects what *this* organization already holds.
"""

from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import select

from app.api.dependencies import CurrentUser, DbSession
from app.api.scoping import OrganizationId
from app.models import Project
from generator_data.importer import catalogue, import_archetypes

router = APIRouter(prefix="/demo-profiles", tags=["Demo profiles"])

MAX_KEYS = 50


class DemoProfile(BaseModel):
    key: str
    name: str
    industry: str
    city: str
    headline_problem: str
    expected_grade: str
    imported: bool
    location_id: str | None


class DemoProfileList(BaseModel):
    items: list[DemoProfile]


class ImportRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    keys: Annotated[list[str], Field(min_length=1, max_length=MAX_KEYS)]
    # The dashboard is project-scoped: a profile in no project shows up in neither the
    # profiles list nor the audit directory. Omitted, each profile brings its own project.
    project_id: UUID | None = None


class ImportedProfile(BaseModel):
    key: str
    location_id: str


class ImportResponse(BaseModel):
    """Keyed, so the UI can name each new profile and link it to its own audit."""

    imported: list[ImportedProfile]
    skipped: list[str]
    unknown: list[str]


@router.get("", response_model=DemoProfileList)
async def list_demo_profiles(
    current_user: CurrentUser, organization_id: OrganizationId, db: DbSession
) -> DemoProfileList:
    return DemoProfileList(items=await catalogue(db, organization_id))


@router.post("/import", response_model=ImportResponse, status_code=status.HTTP_201_CREATED)
async def import_demo_profiles(
    payload: ImportRequest,
    current_user: CurrentUser,
    organization_id: OrganizationId,
    db: DbSession,
) -> ImportResponse:
    """Write the chosen profiles into this organization. Never runs an audit.

    A key this organization already holds is skipped rather than duplicated, and a key no
    archetype declares is reported rather than raised — one stale key from an out-of-date
    picker must not stop the rest of a batch from importing.
    """
    if payload.project_id is not None:
        owns = await db.scalar(
            select(Project.id).where(
                Project.id == payload.project_id, Project.organization_id == organization_id
            )
        )
        if owns is None:
            raise HTTPException(status_code=404, detail="Project not found")

    result = await import_archetypes(
        db, organization_id, payload.keys, project_id=payload.project_id
    )
    await db.commit()
    return ImportResponse(
        imported=[ImportedProfile(**row) for row in result.imported],
        skipped=result.skipped,
        unknown=result.unknown,
    )
